version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    container_name: inventory_mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db

  web:
    build:
      context: .
    container_name: inventory_web
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - mongodb

volumes:
  mongo_data:
